export const contactConstants = {
  GET_ALL_CONTACTS_REQUEST: "GET_ALL_CONTACTS_REQUEST",
  GET_ALL_CONTACTS_SUCCESS: "GET_ALL_CONTACTS_SUCCESS",
  GET_ALL_CONTACTS_FAILURE: "GET_ALL_CONTACTS_FAILURE",

  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  DELETE_CONTACT_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",

  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",
};

export const authConstants = {
  SET_USER: "SET_USER",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  GET_ALL_ARCHIVES:' GET_ALL_ARCHIVES',
  ERRORS: "ERRORS",
};

export const profileConstants = {
  SET_PROFILE: "SET_PROFILE",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  DELETE_PROFILE: "DELETE_PROFILE",
  PROFILE_ERRORS: "PROFILE_ERRORS",
  SEARCH_PROFILES_SUCCESS: " SEARCH_PROFILES_SUCCESS",
  SEARCH_PROFILES_FAILURE: "SEARCH_PROFILES_FAILURE",
  DELETE_PROFILE_SUCCESS: "DELETE_PROFILE_SUCCESS",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",
  MODIFIER_CONTACT_SUCCESS: "MODIFIER_CONTACT_SUCCESS",
  MODIFIER_CONTACT_FAILURE: "MODIFIER_CONTACT_FAILURE",
  PROFILE_REQUEST : "PROFILE_REQUEST",
  MODIFIER_PROFILE_SUCCESS: "MODIFIER_PROFILE_SUCCESS",
  MODIFIER_PROFILE_FAILURE: "MODIFIER_PROFILE_FAILURE",
};
export const archiveConstants = {
  GET_ALL_ARCHIVES:' GET_ALL_ARCHIVES',
  ARCHIVES_ERRORS : 'ARCHIVES_ERRORS',
  DELETE_ARCHIVE_SUCCESS: "DELETE_ARCHIVE_SUCCESS",
  DELETE_ARCHIVE_FAILURE: "DELETE_ARCHIVE_FAILURE",
};
export const newsConstants = {
  GET_ALL_NEWS_REQUEST : 'GET_ALL_NEWS_REQUEST',
  GET_ALL_NEWS:' GET_ALL_NEWS',
  NEWS_ERRORS : 'NEWS_ERRORS',
  ADD_NEWS_REQUEST:'ADD_NEWS_REQUEST',
  ADD_NEWS_SUCCESS:'ADD_NEWS_SUCCESS',
  ADD_NEWS_FAILURE:'ADD_NEWS_FAILURE',
  DELETE_NEWS:'DELETE_NEWS',
  NEWS_ERRORS:'NEWS_ERRORS',
};