export const contactConstants = {
  GET_ALL_CONTACTS_REQUEST: "GET_ALL_CONTACTS_REQUEST",
  GET_ALL_CONTACTS_SUCCESS: "GET_ALL_CONTACTS_SUCCESS",
  GET_ALL_CONTACTS_FAILURE: "GET_ALL_CONTACTS_FAILURE",

  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  DELETE_CONTACT_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",

  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",
};

export const authConstants = {
  SET_USER: "SET_USER",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  GET_ALL_ARCHIVES:' GET_ALL_ARCHIVES',
  ERRORS: "ERRORS",
};

export const profileConstants = {
  SET_PROFILE: "SET_PROFILE",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  DELETE_PROFILE: "DELETE_PROFILE",
  PROFILE_ERRORS: "PROFILE_ERRORS",
  SEARCH_PROFILES_SUCCESS: " SEARCH_PROFILES_SUCCESS",
  SEARCH_PROFILES_FAILURE: "SEARCH_PROFILES_FAILURE",
  DELETE_PROFILE_SUCCESS: "DELETE_PROFILE_SUCCESS",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",
  MODIFIER_CONTACT_SUCCESS: "MODIFIER_CONTACT_SUCCESS",
  MODIFIER_CONTACT_FAILURE: "MODIFIER_CONTACT_FAILURE",
  PROFILE_REQUEST : "PROFILE_REQUEST",
  MODIFIER_PROFILE_SUCCESS: "MODIFIER_PROFILE_SUCCESS",
  MODIFIER_PROFILE_FAILURE: "MODIFIER_PROFILE_FAILURE",
  COUNT_PROFILE:"COUNT_PROFILE",
  COUNT_PROFILE_ERREUR:"COUNT_PROFILE_ERREUR",
};
export const archiveConstants = {
  ARCHIVE_REQUEST : "ARCHIVE_REQUEST",
  GET_ALL_ARCHIVES:' GET_ALL_ARCHIVES',
  ARCHIVES_ERRORS : 'ARCHIVES_ERRORS',
  DELETE_ARCHIVE_SUCCESS: "DELETE_ARCHIVE_SUCCESS",
  DELETE_ARCHIVE_FAILURE: "DELETE_ARCHIVE_FAILURE",
  COUNT_ARCHIVE:"COUNT_ARCHIVE",
  COUNT_ARCHIVE_ERREUR:"COUNT_ARCHIVE_ERREUR",
  MODIFIER_ARCHIVE_SUCCESS:"MODIFIER_ARCHIVE_SUCCESS",
  MODIFIER_ARCHIVE_FAILURE:"MODIFIER_ARCHIVE_FAILURE",
};
export const newsConstants = {
  GET_ALL_NEWS_REQUEST : 'GET_ALL_NEWS_REQUEST',
  GET_ALL_NEWS:' GET_ALL_NEWS',
  NEWS_ERRORS : 'NEWS_ERRORS',
  ADD_NEWS_REQUEST:'ADD_NEWS_REQUEST',
  ADD_NEWS_SUCCESS:'ADD_NEWS_SUCCESS',
  ADD_NEWS_FAILURE:'ADD_NEWS_FAILURE',
  DELETE_NEWS:'DELETE_NEWS',
  NEWS_ERRORS:'NEWS_ERRORS',
  DELETE_DATE_NEWS:'DELETE_DATE_NEWS',

};
export const absenceConstants={
  ADD_ABSENCE_REQUEST:'ADD_ABSENCE_REQUEST',
  ADD_ABSENCE_SUCCESS:'ADD_ABSENCE_SUCCESS',
  ADD_ABSENCE_FAILURE:'ADD_ABSENCE_FAILURE',
  GET_ABSENCE_FAILURE : 'GET_ABSENCE_FAILURE',
  GET_ABSENCE:' GET_ABSENCE',
  GET_ALL_ABSENCE_REQUEST:' GET_ALL_ABSENCE_REQUEST',
  GET_ALL_ABSENCE:' GET_ALL_ABSENCE',
  ABSENCE_ERRORS:'ABSENCE_ERRORS',
  UPDATE_ABSENCE_SUCCESS:'UPDATE_ABSENCE_SUCCESS',
  UPDATE_ABSENCE_FAILURE:'UPDATE_ABSENCE_FAILURE',
  GET_ALL_ABSENCE_ATTENTE_REQUEST:'GET_ALL_ABSENCE_ATTENTE_REQUEST',
  GET_ALL_ABSENCE_ATTENTE:'GET_ALL_ABSENCE_ATTENTE',
}
export const operaConstants = {
  GET_MY_OPERA: 'GET_MY_OPERA',
  OPERA_ERRORS: 'OPERA_ERRORS',
  GET_MY_OPERA_ABSENCE: 'GET_MY_OPERA_ABSENCE',
  OPERA_ABSENCE_ERRORS: 'OPERA_ABSENCE_ERRORS',
  GET_MY_OPERA_ABSENCE_ATTEND:'GET_MY_OPERA_ABSENCE_ATTEND',
  OPERA_ABSENCE_ATTEND_ERRORS:'OPERA_ABSENCE_ATTEND_ERRORS',
};
export const taskConstants = {
ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
ADD_TASK_SUCCESS:'ADD_TASK_SUCCESS',
ADD_TASK_FAILURE:'ADD_TASK_FAILURE',
GET_ALL_TASK_REQUEST:'GET_ALL_TASK_REQUEST',
GET_ALL_TASK:'GET_ALL_TASK',
TASK_ERRORS:'TASK_ERRORS',
DELETE_DATE_TASK:'DELETE_DATE_TASK',
}
export const demandeConstants = {
  ADD_DEMANDE_REQUEST:'ADD_DEMANDE_REQUEST',
  ADD_DEMANDE_SUCCESS:'ADD_DEMANDE_SUCCESS',
  ADD_DEMANDE_FAILURE:'ADD_DEMANDE_FAILURE',
  GET_ALL_DEMANDE_REQUEST:'GET_ALL_DEMANDE_REQUEST',
  GET_ALL_DEMANDE:'GET_ALL_DEMANDE',
  DEMANDE_ERRORS:'DEMANDE_ERRORS',
  UPDATE_DEMANDE_SUCCESS: 'UPDATE_DEMANDE_SUCCESS',
  UPDATE_DEMANDE_FAILURE:'UPDATE_DEMANDE_FAILURE',
  UPDATE_IMAGE_SUCCES:'UPDATE_IMAGE_SUCCES',
  UPDATE_IMAGE_FAILURE:'UPDATE_IMAGE_FAILURE',
}