export const contactConstants = {
  GET_ALL_CONTACTS_REQUEST: "GET_ALL_CONTACTS_REQUEST",
  GET_ALL_CONTACTS_SUCCESS: "GET_ALL_CONTACTS_SUCCESS",
  GET_ALL_CONTACTS_FAILURE: "GET_ALL_CONTACTS_FAILURE",

  ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
  ADD_CONTACT_SUCCESS: "ADD_CONTACT_SUCCESS",
  ADD_CONTACT_FAILURE: "ADD_CONTACT_FAILURE",

  DELETE_CONTACT_REQUEST: "DELETE_CONTACT_REQUEST",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_CONTACT_FAILURE: "DELETE_CONTACT_FAILURE",

  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAILURE: "UPDATE_CONTACT_FAILURE",
};

export const authConstants = {
  SET_USER: "SET_USER",
  ERRORS: "ERRORS",
};

export const profileConstants = {
  SET_PROFILE: "SET_PROFILE",
  GET_ALL_PROFILES: "GET_ALL_PROFILES",
  DELETE_PROFILE: "DELETE_PROFILE",
  PROFILE_ERRORS: "PROFILE_ERRORS",
};
